<!--Hier wird der Chatinhalt gespeichert.-->
<?php include "session.php"; ?>                                                 <!--Verhindert Zugriff ohne eingeloggt zu sein.-->
<tr></td><td>&nbsp;02:28:38&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>!</td></tr>
<tr></td><td>&nbsp;02:28:38&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>"</td></tr>
<tr></td><td>&nbsp;02:28:39&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>§</td></tr>
<tr></td><td>&nbsp;02:28:40&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>E</td></tr>
<tr></td><td>&nbsp;02:28:41&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>Q</td></tr>
<tr></td><td>&nbsp;02:28:42&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>W</td></tr>
<tr></td><td>&nbsp;02:28:43&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>!</td></tr>
<tr></td><td>&nbsp;02:28:44&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>"</td></tr>
<tr></td><td>&nbsp;02:28:44&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>§</td></tr>
<tr></td><td>&nbsp;02:28:45&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>$</td></tr>
<tr></td><td>&nbsp;02:28:47&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;02:28:48&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>2</td></tr>
<tr></td><td>&nbsp;02:28:48&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>3</td></tr>
<tr></td><td>&nbsp;02:28:49&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>4</td></tr>
<tr></td><td>&nbsp;03:40:11&nbsp;</td><td id='chat_entry'><strong>d&nbsp;:</strong><td class='inhalt'>asdf</td></tr>
<tr></td><td>&nbsp;03:49:16&nbsp;</td><td id='chat_entry'><strong>d&nbsp;:</strong><td class='inhalt'>asdf</td></tr>
<tr></td><td>&nbsp;04:51:20&nbsp;</td><td id='chat_entry'><strong>d&nbsp;:</strong><td class='inhalt'>sadf</td></tr>
<tr></td><td>&nbsp;04:54:05&nbsp;</td><td id='chat_entry'><strong>d&nbsp;:</strong><td class='inhalt'>asdf</td></tr>
<tr></td><td>&nbsp;04:54:24&nbsp;</td><td id='chat_entry'><strong>d&nbsp;:</strong><td class='inhalt'>asdf</td></tr>
<tr></td><td>&nbsp;08:15:03&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:03&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:03&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:03&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:04&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:04&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:04&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:04&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:04&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:05&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:05&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:05&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:05&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:06&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:06&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:06&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:06&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:06&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:06&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:07&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:07&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:07&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:07&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:08&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:08&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:08&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:08&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:08&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:09&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:11&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>123</td></tr>
<tr></td><td>&nbsp;08:15:30&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;08:15:48&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>asdfas</td></tr>
<tr></td><td>&nbsp;08:18:14&nbsp;</td><td id='chat_entry'><strong>d&nbsp;:</strong><td class='inhalt'>Kappa</td></tr>
<tr></td><td>&nbsp;08:18:21&nbsp;</td><td id='chat_entry'><strong>d&nbsp;:</strong><td class='inhalt'>kappa</td></tr>
<tr></td><td>&nbsp;08:18:55&nbsp;</td><td id='chat_entry'><strong>d&nbsp;:</strong><td class='inhalt'> <img class='emoticon' src='img/kappa.png'></td></tr>
