<tr></td><td>&nbsp;12:46:19&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:19&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:19&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:20&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:20&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:20&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:20&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:20&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:21&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:21&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:21&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:21&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:22&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:22&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:22&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:22&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:23&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:23&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:23&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:23&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:23&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:24&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:24&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:24&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:24&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:24&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:25&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:25&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:25&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:25&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:25&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:25&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:26&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:26&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:26&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:26&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:26&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:27&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:27&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:27&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:27&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:28&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:28&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:31&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:32&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:32&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:46:32&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>1</td></tr>
<tr></td><td>&nbsp;12:55:15&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>asdfasdf</td></tr>
<tr></td><td>&nbsp;12:55:19&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>fasdfasdf</td></tr>
<tr></td><td>&nbsp;01:04:01&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>asdf</td></tr>
<tr></td><td>&nbsp;01:04:02&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>asdf</td></tr>
<tr></td><td>&nbsp;01:04:02&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>asdf</td></tr>
<tr></td><td>&nbsp;01:05:00&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>asdfasdf</td></tr>
<tr></td><td>&nbsp;01:05:01&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>asfdasdf</td></tr>
<tr></td><td>&nbsp;01:05:02&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>asdfasdf</td></tr>
<tr></td><td>&nbsp;01:05:19&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>asdfasddf</td></tr>
<tr></td><td>&nbsp;01:25:57&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>asdfsadf1213</td></tr>
<tr></td><td>&nbsp;01:40:43&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>test</td></tr>
<tr></td><td>&nbsp;01:41:05&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>asdfasdf</td></tr>
<tr></td><td>&nbsp;01:41:07&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>asdf</td></tr>
<tr></td><td>&nbsp;01:41:07&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>asdf</td></tr>
<tr></td><td>&nbsp;01:41:07&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>as</td></tr>
<tr></td><td>&nbsp;01:41:07&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>df</td></tr>
<tr></td><td>&nbsp;01:41:08&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>sadf</td></tr>
<tr></td><td>&nbsp;12:41:50&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>asdf</td></tr>
<tr></td><td>&nbsp;12:42:30&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>asdf</td></tr>
<tr></td><td>&nbsp;01:09:48&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>Hallo</td></tr>
<tr></td><td>&nbsp;01:16:55&nbsp;</td><td id='chat_entry'><strong>Joel&nbsp;:</strong><td class='inhalt'>asdf</td></tr>
